### ISSUE TITLE
Question on installation

### ISSUE THREAD

**Issue by rhoml** [pingunaut/nexus3-crowd-plugin#20]
I've been trying to install on latest nexus3 but the realm doesn't show up.
After I run `bin/nexus run` And bundle install am i supposed to log into nexus using the admin credentials? 

Also, on the crowd.properties, should it live on sonatype-work/etc? 

also I keep seeing this erros

```1) Error injecting constructor, java.lang.NullPointerException
  at org.sonatype.nexus.crowd.plugin.internal.CachingNexusCrowdClient.<init>(CachingNexusCrowdClient.java:52)
  at / (via modules: org.sonatype.nexus.extender.modules.NexusBundleModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.sonatype.nexus.crowd.plugin.internal.CachingNexusCrowdClient
    for parameter 0 at org.sonatype.nexus.crowd.plugin.internal.CrowdAuthorizationManager.<init>(CrowdAuthorizationManager.java:46)
  at / (via modules: org.sonatype.nexus.extender.modules.NexusBundleModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.sonatype.nexus.crowd.plugin.internal.CrowdAuthorizationManager
  while locating org.sonatype.nexus.security.authz.AuthorizationManager annotated with @com.google.inject.name.Named(value=CrowdAuthorizationManager)

1 error
```

Any idea?

Thanks for your help

**Comment by pingunaut** [comment]
OK I updated the readme to hopefully answer all questions. If there is still something not clear, don't hesitate to ask, I'll try my best to answer

**Comment by webmutation** [comment]
Hi in 

In [$install-dir/etc/] there is a file called org.ops4j.pax.url.mvn.cfg. It contains a property called org.ops4j.pax.url.mvn.repositories. It has to be set to your local maven repository (same as added on step 2):

There is no file by that name in my installation are you sure that is the right path?

**Comment by rhoml** [comment]
Can we create a new release of the plugin?

**Comment by pingunaut** [comment]
Yes, I'll try to get the other issues closed and then create a new tag.
I think we switch to semantic versioning creating a 1.0.0. Seems like sticking to the nexus versioning scheme is not a very good idea

**Comment by pingunaut** [comment]
OK, 1.0.0 was not an option because there are already 3.1.x jars in the field. 
Created 3.2.0: https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.2.0
