### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ridvan70** [pingunaut/nexus3-crowd-plugin#21]
I get the following error, by following your newest installation instructions:
```
Error installing bundle listed in startup.properties with url: mvn:com.pingunaut.nexus/nexus3-crowd-plugin/3.1.0-04 and startlevel: 200
java.lang.NullPointerException
	at org.apache.karaf.main.Main.destroy(Main.java:593)
	at org.sonatype.nexus.karaf.NexusMain.main(NexusMain.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:63)

```
Any hints?

**Comment by ridvan70** [comment]
BTW: I needed to correct the paths to karaf related files
```
[$install-dir/etc/]
```
to
```
[$install-dir/karaf/etc/]
```

**Comment by ridvan70** [comment]
HINT: The local repository linking does not success.
Nexus started successfully after copying the plugin to [$install-dir]/system:
```
cp -ra ~/.m2/repository/com/pingunaut [$install-dir]/system/com/
```

**Comment by pingunaut** [comment]
@ridvan70 Thanks a lot for testing and feedback. I'll update the docs accordingly... I think Karaf and me won't become friends anymore :/

**Comment by webmutation** [comment]
@ridvan70 can you post the step by step of what you did? Do you have it working with 3.1? Thanks :/

**Comment by ridvan70** [comment]
Hi Dan,

Yes, it's the version 3.1.0-04.

Follow the instructions in the README from Martin with the following changes:
1. Use 
```
[$install-dir/karaf/etc/]
```
instead of
```
[$install-dir/etc/]
```
for karaf related paths.

2. Copy the plugin to nexus, after mvn install: 
```
cp -ra ~/.m2/repository/com/pingunaut [$install-dir]/system/com/
```

@pingunaut : Martin, may be you can update the README file with the above information?

Regards,
Ridvan

**Comment by webmutation** [comment]
Excelent! Thanks I was missing one step from the config. everithing seems to be working now :)

**Comment by pingunaut** [comment]
It's already updated in my local repo but nfortunatelly I was not able to push yet. I will do asap and reference #20 in the commit.
