### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ih16** [pingunaut/nexus3-crowd-plugin#26]
Hi, 

We are using Atlassian Crowd Version: 2.10.1 (Build:#685 - 2016-09-13) with version 3.2.0

When we try to login, we receive an 
`2016-12-05 14:44:05,982+0100 INFO  [qtp95839048-99] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - crowd authenticated: false
2016-12-05 14:44:36,373+0100 INFO  [qtp95839048-98] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - doGetAuthenticationInfo for <username omitted> 
2016-12-05 14:44:36,413+0100 ERROR [qtp95839048-98] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.entity.mapper.CrowdMapper - Error with request org.apache.http.client.entity.DecompressingEntity@a39d5b9 - 401`

We verified that the application credentials are correct, and that the application is allowed to login from the crowd side. 

Is the plugin tested with Crowd version 2.10.1? 

Cheers

**Comment by ih16** [comment]
Additional information:

Crowd generates the following error:
`2016-12-05 14:58:02,691 http-bio-8095-exec-9 INFO [plugin.rest.filter.BasicApplicationAuthenticationFilter] Invalid authentication for application with name 'nx'`

while the application credentials are correct

**Comment by ih16** [comment]
Issue has been found and was a hidden problem on our side. You can disregard the issue. 

Cheers

**Comment by pingunaut** [comment]
@ih16 to answer the first question: yes the plugin was tested against crwod 2.10.1

Is there anything I can improve in the documentation so that the issue can be avoided?

**Comment by ih16** [comment]
Hi @pingunaut,

No I think the instructions are clear. in the end, the issue was a invisible trailing whitespace in the crowd.properties that slipped through.. 

Thanks for the reply though! 

Cheers
