### ISSUE TITLE
Nexus 3.5.2 Support and  startup.properties Configuration

### ISSUE THREAD

**Issue by webmutation** [pingunaut/nexus3-crowd-plugin#30]
Hi pingunaut,

I am currently running v3.1.0 of Nexus and v3.1 Crowd plugin. I am preparing a migration to nexus 3.5.2 and 3.2.5 of the Crowd plugin I would like to know if this has been tested. Is 3.2.5 compatible with nexus 3.5.2?

I also see that the configuration of the startup.properties in 3.5.2 has changed from 
`
mvn\:org.apache.felix/org.apache.felix.fileinstall/3.5.4 = 11
mvn\:org.apache.karaf.features/org.apache.karaf.features.core/4.0.5 = 15
mvn\:com.pingunaut.nexus/nexus3-crowd-plugin/3.1.0-04 = 200
`
to this format that just imports the jars and does not point to the directories, should we now import the  nexus3-crowd-plugin-3.2.6-SNAPSHOT.jar ? If so , could you please add a new documentation section to the README

`
reference\:file\:org/jledit/core/0.2.1/core-0.2.1.jar = 30
reference\:file\:org/apache/karaf/diagnostic/org.apache.karaf.diagnostic.boot/4.0.9/org.apache.karaf.diagnostic.boot-4.0.9.jar = 50
`

**Comment by pingunaut** [comment]
Hello @webmutation, sorry for the late answer.
I tested the latest plugin release 3.2.5 with new Nexus 3.6.0 and it works just fine so I don't think there are any problems with an older Nexus.

You are right the format for imports has changed and I'll update that (however it's still working fine with the old mvn:\ way of configuration). Thanks a lot for your feedback!

**Comment by webmutation** [comment]
Thank you very much for this, your work is much appreciated!

I can now upgrade my repository with confidence :smile:

**Comment by pingunaut** [comment]
Np, would be glad to hear if everything went well afterwards 👍
