### ISSUE TITLE
Delete external role mapping but user still have access

### ISSUE THREAD

**Issue by eyckluo** [pingunaut/nexus3-crowd-plugin#47]
Hi

I did some tries for this, but seems when I deleted a mapped role in nexus, the users of role still have the right access to nexus, may I know if there a scheduler of data sync? in nexus2, it is "cacheTTL" default to 1 hour. and if has a scheduler, what is the impact if I make this time shorter?

Thanks
Eyck

**Comment by pingunaut** [comment]
Hi @eyckluo,

The cache lifetime in nexus3-crowd-plugin is currently set to 15 minutes here:
https://github.com/pingunaut/nexus3-crowd-plugin/blob/master/src/main/java/com/pingunaut/nexus3/crowd/plugin/internal/CacheProvider.java#L28

It is not configurable at all. If this is a requirement for you, please open a separate issue to implement this feature.

Does this answer your question?

Best regards,
Martin

**Comment by eyckluo** [comment]
Hi Martin

Thanks your answer, we dont really need to modify this.

Best regards,
Eyck

**Comment by pingunaut** [comment]
Allright. Will close this now. If it comes up in as a requirement, don't hesitate to raise an issue again. for the moment I think it's a good idea to keep the plugin as simple as possile
