### ISSUE TITLE
Put config in sonatype-work (data-dir)

### ISSUE THREAD

**Issue by jvdmr** [pingunaut/nexus3-crowd-plugin#50]
All other config for Nexus is in the data dir, allowing nexus admins to upgrade the application by simply removing the install dir and unzipping the new version. crowd.properties should be in $data-dir/nexus3/etc, not in $install-dir/etc

**Comment by pingunaut** [comment]
@jvdmr Thanks a lot for your input.
You can download a new release jar at https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.4.0
Can you have a look if this works for you and give a short feedback?

**Comment by jvdmr** [comment]
Works perfectly, thank you very much!

**Comment by pingunaut** [comment]
Cool, thank you top :)
