### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by gopal9590** [pingunaut/nexus3-crowd-plugin#54]
Thank you for the cool plugin !

I am using nexus OSS version 3.9 and crowd plugin version 3.2.7 , nexus is running behind nginx reverse proxy : Though all the valid certs are loaded but still it doesnt seems to be able to authenticate to crowd server.
do you think the plugin version could be an issue or Can you please suggest what could be the root cause ?

Appreciate your support !

############################################################################

2018-05-21 10:24:51,839-0500 INFO  [qtp520303092-41] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.CrowdAuthenticatingRealm - doGetAuthenticationInfo for tools-admin
2018-05-21 10:24:51,919-0500 ERROR [qtp520303092-41] *UNKNOWN com.pingunaut.nexus3.crowd.plugin.internal.CachingNexusCrowdClient - error executng query
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)

**Comment by pingunaut** [comment]
Thanks a lot 😃 
I think a similar issue was already answered here: https://github.com/pingunaut/nexus3-crowd-plugin/issues/28#issuecomment-323515446

I hope this will work for you also.. 
I don't think this is a version problem or a problem of the plugin itself. Keep me updated

**Comment by gopal9590** [comment]
Thank you so much for your response , Martin !

I had looked at that article of yours earlier and made sure on that.

Though I retried it just to be double sure (validated that certs are
already present ) , somehow its still not working.

Just to provide more details : The plugin version 3.2.7 with nexus version
3.6.2 is working good without the need to load the ssl certs.
but for plugin version 3.2.7/3.3.0 with nexus 3.8 and above , I am having
issues with the same error as unable to find the valid certification path

Can you kindly help and please let me know if any further details needed

Thanks again !

Appreciate your support

Regards
Gopal

**Comment by pingunaut** [comment]
Hi Gopal,

I can only repeat: The plugin does not implement any certificate validation related stuff by itself.
Instead it uses the standard Java libraries.

Maybe you can verify that you use the same Java installation for both versions of Nexus. You can so so in the "System Information"
There is a property called "java.home".  Is "java.home" equal for both versions of Nexus?
![image](https://user-images.githubusercontent.com/1359917/40384398-b4e6596a-5e03-11e8-9670-09eac5dbcf9b.png)

**Comment by gopal9590** [comment]
Thank you so much , Martin

Greatly Appreciate your help !

you were right , I just figured out somehow java.home was coming
differently with my Dockerfile

It's fixed and working for me :)

You have a blessed day !

Thanks again

**Comment by pingunaut** [comment]
Cool, thanks for the feedback!
I'm glad I was able to help and that everything is working for you now :+1:
