### ISSUE TITLE
Nexus OSS 3.12.x

### ISSUE THREAD

**Issue by mvdkleijn** [pingunaut/nexus3-crowd-plugin#55]
Hi @pingunaut ,

Great work on this plugin! Does nexus3-crowd-plugin-3.4.0 support Nexus OSS 3.12.x? The code suggests yes?

Also, can you elaborate why its a pre-release (before I put it in production)?

Thanks!

**Comment by pingunaut** [comment]
Hi @mvdkleijn,
it's considered a pre-release because I did not yet receive feedback for issue #48

I did not have the chance to test with 3.12 yet, but i'm pretty sure it will work, as the last minor Nexus updates did not require any code changes.

**Comment by mvdkleijn** [comment]
Thanks for the information. :+1: Sounds like this will be no problem for our purposes. I'll keep an eye on the final release and test with the pre-release if the final one is not available on time for our test setup.

Closing issue.
