### ISSUE TITLE
RUT auth does not work

### ISSUE THREAD

**Issue by vbier** [pingunaut/nexus3-crowd-plugin#59]
See https://github.com/PatrickRoumanoff/nexus-crowd-plugin/issues/32 for a description of the problem and the fix.

**Comment by pingunaut** [comment]
Hi @vbier 
https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.4.3-beta1 has been released.
Can you give a short feedback if this fixes your problem?

**Comment by vbier** [comment]
Works with the provided beta jar. Thanks for fixing this.
