### ISSUE TITLE
Error after plugin installation 

### ISSUE THREAD

**Issue by vliloia** [pingunaut/nexus3-crowd-plugin#6]
Right after installation of the plugin on Nexus 3.0.0-03 we're facing a NullPointerException. Any Idea on what could be the reason for it? Installation was done according to the documentation.

	2016-05-24 14:23:33,978+0200 WARN  [qtp203236089-666] admin org.sonatype.nexus.rapture.internal.state.StateComponent - Failed to get state from com.google.inject.internal.InjectorImpl$2 (ignored)
	com.google.inject.ProvisionException: Unable to provision, see the following errors:
	
	1) Error injecting constructor, java.lang.NullPointerException
	  at org.sonatype.nexus.crowd.plugin.internal.CachingNexusCrowdClient.<init>(CachingNexusCrowdClient.java:52)
	  at / (via modules: org.sonatype.nexus.extender.modules.NexusBundleModule -> org.eclipse.sisu.space.SpaceModule)
	  while locating org.sonatype.nexus.crowd.plugin.internal.CachingNexusCrowdClient
	    for parameter 0 at org.sonatype.nexus.crowd.plugin.internal.CrowdAuthorizationManager.<init>(CrowdAuthorizationManager.java:46)
	  at / (via modules: org.sonatype.nexus.extender.modules.NexusBundleModule -> org.eclipse.sisu.space.SpaceModule)
	  while locating org.sonatype.nexus.crowd.plugin.internal.CrowdAuthorizationManager
	  while locating org.sonatype.nexus.security.authz.AuthorizationManager annotated with @com.google.inject.name.Named(value=CrowdAuthorizationManager)
	  
Environment: Linux version 3.0.101-0.47.52-default (SUSE Linux)
Sonatype Nexus: 3.0.0-03 OSS
Plugin Version: nexus3-crowd-plugin-3.0.0-03

Thanks in advance.

**Comment by pingunaut** [comment]
Argh, I forgot to mention one important point in the readme.

Place a crowd.properties file in [install_dir]/etc
The file has to contain the following properties:
crowd.server.url (e.g. http://localhost:8095/crowd)
application.name
application.password

These properties are needed to tell nexus about your crowd setup. I'll update docs as soons as possible

**Comment by vliloia** [comment]
Thanks for your fast answer. It looks good after doing that.

**Comment by pingunaut** [comment]
comment was added to readme
