### ISSUE TITLE
Only 1000 groups supported

### ISSUE THREAD

**Issue by bartdevriendt** [pingunaut/nexus3-crowd-plugin#65]
The method to fetch groups from Crowd does 1 search which is limited to 1000 groups.  It should loop through all pages to fetch all groups.

**Comment by sonata82** [comment]
I'm running into this issue as well. It stems from the fact that the GET query `search`, which is called by `NexusCrowdClient.findRoles()`,  does have a default maximum of 1000 ([see here](https://docs.atlassian.com/atlassian-crowd/3.3.0/REST/#usermanagement/1/search-search)).

Does it make more sense to enhance the `CachingNexusCrowdClient` to support pagination or should we just add a `max-results=Integer.MAX_VALUE` to the HTTP query?

**Comment by pingunaut** [comment]
@sonata82 I think we should go for pagination, as it seems that the `max-results` support is being dropped by Atlassian (At least it has already been dropped for JIRA api, see [How to get more than 50 issues with search API](https://community.atlassian.com/t5/Jira-questions/How-to-get-more-than-50-issues-with-search-API/qaq-p/463122))

Unfortunately all requests are built 'by hand' as Crowd API Client comes with a load of dependencies causing compatibility issues with Nexus. Would be great to have a helping hand here. Work already started in branch [65-groups](https://github.com/pingunaut/nexus3-crowd-plugin/tree/65-groups), but not much done yet...

**Comment by sonata82** [comment]
I'll start by adding some test cases :)

**Comment by jonesbusy** [comment]
Is the the same issue with findUsers() method ? I guess pagination should be added there as well ?

**Comment by jonesbusy** [comment]
Any update on this ? Let me know if you need help to test the pagination :)

**Comment by pingunaut** [comment]
@sonata82 ? :)

**Comment by pingunaut** [comment]
Thanks a lot for your patience. This is fixed with [nexus3-crowd-plugin-3.6.0](https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.6.0)
