### ISSUE TITLE
Question: Does this plugin work with npm repositories?

### ISSUE THREAD

**Issue by tobilarscheid** [pingunaut/nexus3-crowd-plugin#77]
Hi Martin,

not really an issue, rather a question, maybe you have an idea: We are running a github oauth plugin for nexus and (as we admit in our credits section ;-) ) a lot of the initial code is inspired by your plugin. Unfortunately, we are absolutely failing to make it work with nexus npm repositories - see [nexus3-github-oauth/#24](https://github.com/larscheid-schmitzhermes/nexus3-github-oauth-plugin/issues/24) for details. We also opened an issue with the nexus guys, but to be honest they don't seem very supportive of plugin developers in general.

So anyways, maybe you have an idea or could even test your own plugin against an npm repository. Would love to join forces here.

Thanks in advance and keep up the good work,

Tobi

**Comment by pingunaut** [comment]
@mrmunch can you answer this question?

**Comment by pingunaut** [comment]
Just found an old issue from 2016: #27 
So it seems that at least it worked some time ago. I'll try to have a deeper look at it asap but probably won't make it until the weekend :/
Thanks for the credits! :+1: :smiley: (and yes I share your opinion on nexus support. I contacted them once, but didn't receive an answer at all...)

**Comment by tobilarscheid** [comment]
I found the issue as well, but to me it looks like the guy created a local npm user, not a user in crowd. Anyways, everything you can dig up helps :-)

**Comment by pingunaut** [comment]
fixed with version 3.8.0
https://github.com/pingunaut/nexus3-crowd-plugin/releases/tag/nexus3-crowd-plugin-3.8.0
