### ISSUE TITLE
Question: Does the latest plugin support for Nexus Repository 3.17.0?

### ISSUE THREAD

**Issue by johansoetewey** [pingunaut/nexus3-crowd-plugin#80]
Does the latest plugin version support for Nexus Repository 3.17.0?

Kind regards,
Johan

**Comment by pingunaut** [comment]
Hi @johansoetewey 
unfortunately I was not yet albe to verify. But as #75 is still unresolved, I assume it also won't work in 3.17.0 :disappointed: 
Any help/test appreciated

**Comment by langsweirdt** [comment]
I have tested crowd plugin 3.7.1 with Nexus Repository OSS 3.17.0-01 (and Atlassian Crowd Server 3.5.0, Build:#1120). Plugin is working as advertised. I assume this issue can be closed.

**Comment by jonesbusy** [comment]
Hey!

On my side I've just tested the latest version (3.8.0) and works like a charm with Nexus 3.20.1. For the moment no issue found :)

Thanks!
