### ISSUE TITLE
Nexus goes into disconnect/reconnect endless cycle when Crowd realm is activated

### ISSUE THREAD

**Issue by netropic** [pingunaut/nexus3-crowd-plugin#9]
After installing plugin and activating Crowd realm, the Web interface goes into an endless cycle of "Server disconnected" and "There is a problem communicating with the server".  UI is still usable but you have to continually click Retry button.

Log shows this:
016-08-09 12:08:15,048-0400 INFO  [qtp1637593904-178] admin #org.sonatype.nexus.crowd.plugin.internal.CachingNexusCrowdClient - getting groups from https://my-crowd-host/crowd//rest/usermanagement/1/user/group/nested?username=admin

When trying to create an external role mapping, this error dialog appears:
"Authorization-manager with source 'Crowd' could not be found"

"Server disconnected" alerts stop coming when Crowd realm is removed from active list.

Crowd is 2.7.2, Nexus is 3.0.1-01.

**Comment by netropic** [comment]
Hmm this may be because of trailing / in Crowd URL.... testing further...

**Comment by netropic** [comment]
Confirmed. Trailing / in Crowd URL causes these problems. Sorry for false alarm!

**Comment by pingunaut** [comment]
Thanks for the fast feedback. Just got the test environment up and running :)
I think a trailing / should not cause such an error though. I will reopen this issue and try to fix this during the next days. 

Best regards,
Martin
